### ISSUE TITLE
UDS 4 Data Persistence Phase 1

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-api#25]
```[tasklist]
### Tasks
- [ ] #24
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-api/issues/32
- [x] Data Persistence for A2
- [x] Data Persistence for A3
- [x] Data Persistence for A4
- [x] Data Persistence for A4a
- [x] Data Persistence for A5-D2
- [x] Data Persistence for B1
- [x] Data Persistence for B3
- [x] Data Persistence for B8
- [x] Data Persistence for B9
- [x] Data Persistence for C2
- [x] Data Persistence for D1a
- [x] Data Persistence for D1b
```
