### ISSUE TITLE
Data Persistence for A2

### ISSUE THREAD

**Issue by smiththay** [UK-SBCoA/uniform-data-set-dotnet-api#35]
```[tasklist]
### Tasks
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-api/issues/29
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-api/issues/30
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet-api/issues/31
```
