### ISSUE TITLE
Upgrade Participations with GetByLegacyId

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet-api#7]
Upgrade IParticipationsClient, ParticipationsClient, and Participations controller with functionality to get participation by Legacy Id.

```[tasklist]
### Tasks
- [x] Add methods to API Wrapper: IParticipationsClient and ParticipationsClient
- [x] Update ParticipationsController with new endpoint (include OpenAPI spec attribute
- [x] Upgrade semantic version of solution, UDS.Net.API.Client, and UDS.Net.Dto packages
- [ ] Tag commit with version **MUST** follow exact format `v*.*.*`
```

https://github.com/UK-SBCoA/uniform-data-set-dotnet-api/blob/3b3273af7dc5d5f70915a427f16eae9bb8dfb15b/src/UDS.Net.API.Client/IParticipationClient.cs#L8

**Comment by AhmedMustafa2201** [comment]
@ashleybot could you please assign this issue to me to start working?
